<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6886e3d1-2daa-45d1-98d6-1f3bb715ffd2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\biblioteket.ApiService\biblioteket.ApiService.csproj" />
    <ProjectReference Include="..\biblioteket.Web\biblioteket.Web.csproj" />
    <ProjectReference Include="..\biblioteket.Worker\biblioteket.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.1.0" />
  </ItemGroup>

</Project>
