<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\biblioteket.Data\biblioteket.Data.csproj" />
    <ProjectReference Include="..\biblioteket.ServiceDefaults\biblioteket.ServiceDefaults.csproj" />
    <ProjectReference Include="..\biblioteket.Services\biblioteket.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
  </ItemGroup>

</Project>
