FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["biblioteket.ApiService/biblioteket.ApiService.csproj", "biblioteket.ApiService/"]
COPY ["biblioteket.ServiceDefaults/biblioteket.ServiceDefaults.csproj", "biblioteket.ServiceDefaults/"]
RUN dotnet restore "biblioteket.ApiService/biblioteket.ApiService.csproj"
COPY . .
WORKDIR "/src/biblioteket.ApiService"
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "biblioteket.ApiService.dll"]