// <auto-generated />
using System;
using Biblioteket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace biblioteket.Data.Migrations
{
    [DbContext(typeof(BiblioteketDbContext))]
    [Migration("20260409141123_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Biblioteket.Data.Bok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HämtatLegimusInformationTidpunkt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InläsareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegimusUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InläsareId");

                    b.ToTable("Böcker");
                });

            modelBuilder.Entity("Biblioteket.Data.Författare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Författare");
                });

            modelBuilder.Entity("Biblioteket.Data.Inläsare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inläsare");
                });

            modelBuilder.Entity("Biblioteket.Data.Nedladdning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BokId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tidpunkt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BokId");

                    b.ToTable("Nedladdningar");
                });

            modelBuilder.Entity("BokFörfattare", b =>
                {
                    b.Property<int>("BöckerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FörfattareId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BöckerId", "FörfattareId");

                    b.HasIndex("FörfattareId");

                    b.ToTable("BokFörfattare");
                });

            modelBuilder.Entity("Biblioteket.Data.Bok", b =>
                {
                    b.HasOne("Biblioteket.Data.Inläsare", "Inläsare")
                        .WithMany("Böcker")
                        .HasForeignKey("InläsareId");

                    b.Navigation("Inläsare");
                });

            modelBuilder.Entity("Biblioteket.Data.Nedladdning", b =>
                {
                    b.HasOne("Biblioteket.Data.Bok", null)
                        .WithMany("Nedladdningar")
                        .HasForeignKey("BokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BokFörfattare", b =>
                {
                    b.HasOne("Biblioteket.Data.Bok", null)
                        .WithMany()
                        .HasForeignKey("BöckerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteket.Data.Författare", null)
                        .WithMany()
                        .HasForeignKey("FörfattareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biblioteket.Data.Bok", b =>
                {
                    b.Navigation("Nedladdningar");
                });

            modelBuilder.Entity("Biblioteket.Data.Inläsare", b =>
                {
                    b.Navigation("Böcker");
                });
#pragma warning restore 612, 618
        }
    }
}
